# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-alpine

# Set working directory
WORKDIR /app

# Install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . ./

# Expose port 8080 (if required by the app's http server, though it's using stdio, might not be needed)
EXPOSE 8080

# Set the command to run the MCP server
CMD ["python", "server.py"]
