# Generated by https://smithery.ai. See: https://smithery.ai/docs/config#dockerfile
FROM python:3.10-slim

WORKDIR /app

# Copy requirements and install dependencies
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the application code
COPY . .

# Append main block to ensure the MCP server runs and listens
RUN echo "\nif __name__ == '__main__':\n    mcp.run()" >> server.py

# Expose port for the MCP server (http://localhost:8080)
EXPOSE 8080

# Command to run the server
CMD ["python", "server.py"]
