services:
  - type: web
    name: my-python-app
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    envVars:
      - key: MY_ENV_VAR
        value: my_value # Replace with your actual environment variables if needed
    autoDeploy: true
