services:
  - type: web
    name: mcp-demo
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python server.py
    autoDeploy: true
    envVars:
      - key: PORT
        value: 8000  # Render overrides this